In [1]:
!pip install -Uqq fastbook

In [2]:
import fastbook
fastbook.setup_book()

In [3]:
#hide $error ModuleNotFoundError: No module named 'fastai.gen_doc'
#from fastai.gen_doc.nbdoc import *

# A Neural Net from the Foundations

## Building a Neural Net Layer from Scratch

### Modeling a Neuron

### Matrix Multiplication from Scratch
Let's write a function that computes the matrix product of two tensors, before we allow ourselves to use the PyTorch version of it. We will only use the indexing in PyTorch tensors:

In [4]:
import numpy as np
import torch
from torch import tensor

We'll need three nested `for` loops:  
- i for the row indices  
- j for the column indices, and  
- k for the inner sum (ac==br)

In [5]:
#define function
#dstruct: use indexing in torch tensor
#need 3 nested loops: i for row indices, j for col indices, k for the inner sum (ac==br)
def matmul(a,b):
    ar,ac = a.shape # n_rows * n_cols
    br,bc = b.shape
    assert ac==br
    c = torch.zeros(ar, bc)
    for i in range(ar):
        for j in range(bc):
            for k in range(ac): c[i,j] += a[i,k] * b[k,j]
    return c

In [6]:
#define tensors
m1 = torch.randn(5,28*28)
m2 = torch.randn(784,10)

m1.shape, m2.shape

(torch.Size([5, 784]), torch.Size([784, 10]))

Let's time our function, using the Jupyter "magic" command `%time`:

In [7]:
%time t1=matmul(m1, m2)

CPU times: user 1.01 s, sys: 2.29 ms, total: 1.01 s
Wall time: 1.01 s


And see how that compares to PyTorch's built-in `@`:

In [8]:
%timeit -n 20 t2=m1@m2

The slowest run took 30.06 times longer than the fastest. This could mean that an intermediate result is being cached.
38 µs ± 74.1 µs per loop (mean ± std. dev. of 7 runs, 20 loops each)


As we can see, in Python three nested loops is a very bad idea! Python is a slow language, and this isn't going to be very efficient. We see here that PyTorch is around 100,000 times faster than Python—and that's before we even start using the GPU!

Where does this difference come from? PyTorch didn't write its matrix multiplication in Python, but rather in C++ to make it fast. In general, whenever we do computations on tensors we will need to *vectorize* them so that we can take advantage of the speed of PyTorch, usually by using two techniques: elementwise arithmetic and broadcasting.

In [9]:
#my MatMul w/torch
#src https://pytorch.org/docs/stable/generated/torch.matmul.html

print(torch.matmul(m1,m2).size())
print(torch.matmul(m1,m2))
%time torch_matmul=torch.matmul(m1,m2)

torch.Size([5, 10])
tensor([[ 24.4247, -14.3996,  38.5341,  77.2113, -10.4177,  26.7255,  20.0069, -20.6713,   4.6560, -30.0900],
        [ -1.5383, -25.5927, -17.6726,  33.6043,   2.1063,  -7.6736, -25.8539, -85.6422,  11.2662,  53.2808],
        [ 44.6554, -39.9383, -26.3721,  28.6456, -15.0637,   7.8983, -16.4531, -17.2903, -36.5638,   7.7106],
        [ 10.8838, -31.5166,  28.7179,  33.3447,  13.2409, -40.4614, -50.5393, -25.0790,   4.7932,  -5.1468],
        [  3.0999,  18.2041,  34.2513, -46.1954, -19.2378, -43.5744,  -5.8470,  -9.7701, -26.3726, -30.8362]])
CPU times: user 0 ns, sys: 476 µs, total: 476 µs
Wall time: 417 µs


In [10]:
m1@m2

tensor([[ 24.4247, -14.3996,  38.5341,  77.2113, -10.4177,  26.7255,  20.0069, -20.6713,   4.6560, -30.0900],
        [ -1.5383, -25.5927, -17.6726,  33.6043,   2.1063,  -7.6736, -25.8539, -85.6422,  11.2662,  53.2808],
        [ 44.6554, -39.9383, -26.3721,  28.6456, -15.0637,   7.8983, -16.4531, -17.2903, -36.5638,   7.7106],
        [ 10.8838, -31.5166,  28.7179,  33.3447,  13.2409, -40.4614, -50.5393, -25.0790,   4.7932,  -5.1468],
        [  3.0999,  18.2041,  34.2513, -46.1954, -19.2378, -43.5744,  -5.8470,  -9.7701, -26.3726, -30.8362]])

### Elementwise Arithmetic

In [11]:
a = tensor([10., 6, -4])
b = tensor([2., 8, 7])
a + b

tensor([12., 14.,  3.])

In [12]:
a < b

tensor([False,  True,  True])

In [13]:
(a < b).all(), (a==b).all()

(tensor(False), tensor(False))

In [14]:
(a + b).mean().item()

9.666666984558105

In [15]:
m = tensor([[1., 2, 3], [4,5,6], [7,8,9]])
m*m

tensor([[ 1.,  4.,  9.],
        [16., 25., 36.],
        [49., 64., 81.]])

In [16]:
n = tensor([[1., 2, 3], [4,5,6]])
m*n

RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 0

With elementwise arithmetic, we can remove one of our three nested loops: we can multiply the tensors that correspond to the `i`-th row of `a` and the `j`-th column of `b` before summing all the elements, which will speed things up because the inner loop will now be executed by PyTorch at C speed. 

To access one column or row, we can simply write `a[i,:]` (can be abbreviated to `a[i]`) or `b[:,j]`. With all of that in mind, we can write a new version of our matrix multiplication:

In [17]:
def matmul(a,b):
    ar,ac = a.shape
    br,bc = b.shape
    assert ac==br
    c = torch.zeros(ar, bc)
    for i in range(ar):
        for j in range(bc): c[i,j] = (a[i] * b[:,j]).sum()
    return c

In [18]:
%timeit -n 20 t3 = matmul(m1,m2)

1.53 ms ± 96.5 µs per loop (mean ± std. dev. of 7 runs, 20 loops each)


### Broadcasting

#### Broadcasting with a scalar

In [19]:
a = tensor([10., 6, -4])
a > 0

tensor([ True,  True, False])

In [20]:
m = tensor([[1., 2, 3], [4,5,6], [7,8,9]])
(m - 5) / 2.73

tensor([[-1.4652, -1.0989, -0.7326],
        [-0.3663,  0.0000,  0.3663],
        [ 0.7326,  1.0989,  1.4652]])

#### Broadcasting a vector to a matrix

In [21]:
c = tensor([10.,20,30])
m = tensor([[1., 2, 3], [4,5,6], [7,8,9]])
m.shape,c.shape

(torch.Size([3, 3]), torch.Size([3]))

In [22]:
m + c

tensor([[11., 22., 33.],
        [14., 25., 36.],
        [17., 28., 39.]])

In [23]:
c.expand_as(m)

tensor([[10., 20., 30.],
        [10., 20., 30.],
        [10., 20., 30.]])

In [24]:
t = c.expand_as(m)
t.storage()

 10.0
 20.0
 30.0
[torch.FloatStorage of size 3]

In [25]:
t.stride(), t.shape

((0, 1), torch.Size([3, 3]))

In [26]:
c + m

tensor([[11., 22., 33.],
        [14., 25., 36.],
        [17., 28., 39.]])

In [27]:
c = tensor([10.,20,30])
m = tensor([[1., 2, 3], [4,5,6]])
c+m

tensor([[11., 22., 33.],
        [14., 25., 36.]])

In [28]:
c = tensor([10.,20])
m = tensor([[1., 2, 3], [4,5,6]])
c+m

RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 1

In [29]:
c = tensor([10.,20,30])
m = tensor([[1., 2, 3], [4,5,6], [7,8,9]])
c = c.unsqueeze(1)
m.shape,c.shape

(torch.Size([3, 3]), torch.Size([3, 1]))

In [30]:
c+m

tensor([[11., 12., 13.],
        [24., 25., 26.],
        [37., 38., 39.]])

In [31]:
t = c.expand_as(m)
t.storage()

 10.0
 20.0
 30.0
[torch.FloatStorage of size 3]

In [32]:
t.stride(), t.shape

((1, 0), torch.Size([3, 3]))

In [33]:
c = tensor([10.,20,30])
c.shape, c.unsqueeze(0).shape,c.unsqueeze(1).shape

(torch.Size([3]), torch.Size([1, 3]), torch.Size([3, 1]))

In [34]:
c.shape, c[None,:].shape,c[:,None].shape

(torch.Size([3]), torch.Size([1, 3]), torch.Size([3, 1]))

In [35]:
c[None].shape,c[...,None].shape

(torch.Size([1, 3]), torch.Size([3, 1]))

In [36]:
def matmul(a,b):
    ar,ac = a.shape
    br,bc = b.shape
    assert ac==br
    c = torch.zeros(ar, bc)
    for i in range(ar):
        c[i] = (a[i] * b.T).sum(1)
    return c

In [37]:
def matmul(a,b):
    ar,ac = a.shape
    br,bc = b.shape
    assert ac==br
    c = torch.zeros(ar, bc)
    for i in range(ar):
#       c[i,j] = (a[i,:]          * b[:,j]).sum() # previous
#       c[i] = (a[i] * b.T).sum(1) # my
        c[i]   = (a[i].unsqueeze(-1) * b).sum(dim=0)
    return c

In [41]:
%timeit -n 20 t4 = matmul(m1,m2)

268 µs ± 29.3 µs per loop (mean ± std. dev. of 7 runs, 20 loops each)


In [39]:
mystop

NameError: name 'mystop' is not defined

#### Broadcasting rules

### Einstein Summation

In [ ]:
def matmul(a,b): return torch.einsum('ik,kj->ij', a, b)

In [ ]:
%timeit -n 20 t5 = matmul(m1,m2)

## The Forward and Backward Passes

### Defining and Initializing a Layer

In [ ]:
def lin(x, w, b): return x @ w + b

In [ ]:
x = torch.randn(200, 100)
y = torch.randn(200)

In [ ]:
w1 = torch.randn(100,50)
b1 = torch.zeros(50)
w2 = torch.randn(50,1)
b2 = torch.zeros(1)

In [ ]:
l1 = lin(x, w1, b1)
l1.shape

In [ ]:
l1.mean(), l1.std()

In [ ]:
x = torch.randn(200, 100)
for i in range(50): x = x @ torch.randn(100,100)
x[0:5,0:5]

In [ ]:
x = torch.randn(200, 100)
for i in range(50): x = x @ (torch.randn(100,100) * 0.01)
x[0:5,0:5]

In [ ]:
x = torch.randn(200, 100)
for i in range(50): x = x @ (torch.randn(100,100) * 0.1)
x[0:5,0:5]

In [ ]:
x.std()

In [ ]:
x = torch.randn(200, 100)
y = torch.randn(200)

In [ ]:
from math import sqrt
w1 = torch.randn(100,50) / sqrt(100)
b1 = torch.zeros(50)
w2 = torch.randn(50,1) / sqrt(50)
b2 = torch.zeros(1)

In [ ]:
l1 = lin(x, w1, b1)
l1.mean(),l1.std()

In [ ]:
def relu(x): return x.clamp_min(0.)

In [ ]:
l2 = relu(l1)
l2.mean(),l2.std()

In [ ]:
x = torch.randn(200, 100)
for i in range(50): x = relu(x @ (torch.randn(100,100) * 0.1))
x[0:5,0:5]

In [ ]:
x = torch.randn(200, 100)
for i in range(50): x = relu(x @ (torch.randn(100,100) * sqrt(2/100)))
x[0:5,0:5]

In [ ]:
x = torch.randn(200, 100)
y = torch.randn(200)

In [ ]:
w1 = torch.randn(100,50) * sqrt(2 / 100)
b1 = torch.zeros(50)
w2 = torch.randn(50,1) * sqrt(2 / 50)
b2 = torch.zeros(1)

In [ ]:
l1 = lin(x, w1, b1)
l2 = relu(l1)
l2.mean(), l2.std()

In [ ]:
def model(x):
    l1 = lin(x, w1, b1)
    l2 = relu(l1)
    l3 = lin(l2, w2, b2)
    return l3

In [ ]:
out = model(x)
out.shape

In [ ]:
def mse(output, targ): return (output.squeeze(-1) - targ).pow(2).mean()

In [ ]:
loss = mse(out, y)

### Gradients and the Backward Pass

In [ ]:
def mse_grad(inp, targ): 
    # grad of loss with respect to output of previous layer
    inp.g = 2. * (inp.squeeze() - targ).unsqueeze(-1) / inp.shape[0]

In [ ]:
def relu_grad(inp, out):
    # grad of relu with respect to input activations
    inp.g = (inp>0).float() * out.g

In [ ]:
def lin_grad(inp, out, w, b):
    # grad of matmul with respect to input
    inp.g = out.g @ w.t()
    w.g = inp.t() @ out.g
    b.g = out.g.sum(0)

### Sidebar: SymPy

In [ ]:
from sympy import symbols,diff
sx,sy = symbols('sx sy')
diff(sx**2, sx)

### End sidebar

In [ ]:
def forward_and_backward(inp, targ):
    # forward pass:
    l1 = inp @ w1 + b1
    l2 = relu(l1)
    out = l2 @ w2 + b2
    # we don't actually need the loss in backward!
    loss = mse(out, targ)
    
    # backward pass:
    mse_grad(out, targ)
    lin_grad(l2, out, w2, b2)
    relu_grad(l1, l2)
    lin_grad(inp, l1, w1, b1)

### Refactoring the Model

In [ ]:
class Relu():
    def __call__(self, inp):
        self.inp = inp
        self.out = inp.clamp_min(0.)
        return self.out
    
    def backward(self): self.inp.g = (self.inp>0).float() * self.out.g

In [ ]:
class Lin():
    def __init__(self, w, b): self.w,self.b = w,b
        
    def __call__(self, inp):
        self.inp = inp
        self.out = inp@self.w + self.b
        return self.out
    
    def backward(self):
        self.inp.g = self.out.g @ self.w.t()
        self.w.g = self.inp.t() @ self.out.g
        self.b.g = self.out.g.sum(0)

In [ ]:
class Mse():
    def __call__(self, inp, targ):
        self.inp = inp
        self.targ = targ
        self.out = (inp.squeeze() - targ).pow(2).mean()
        return self.out
    
    def backward(self):
        x = (self.inp.squeeze()-self.targ).unsqueeze(-1)
        self.inp.g = 2.*x/self.targ.shape[0]

In [ ]:
class Model():
    def __init__(self, w1, b1, w2, b2):
        self.layers = [Lin(w1,b1), Relu(), Lin(w2,b2)]
        self.loss = Mse()
        
    def __call__(self, x, targ):
        for l in self.layers: x = l(x)
        return self.loss(x, targ)
    
    def backward(self):
        self.loss.backward()
        for l in reversed(self.layers): l.backward()

In [ ]:
model = Model(w1, b1, w2, b2)

In [ ]:
loss = model(x, y)

In [ ]:
model.backward()

### Going to PyTorch

In [ ]:
class LayerFunction():
    def __call__(self, *args):
        self.args = args
        self.out = self.forward(*args)
        return self.out
    
    def forward(self):  raise Exception('not implemented')
    def bwd(self):      raise Exception('not implemented')
    def backward(self): self.bwd(self.out, *self.args)

In [ ]:
class Relu(LayerFunction):
    def forward(self, inp): return inp.clamp_min(0.)
    def bwd(self, out, inp): inp.g = (inp>0).float() * out.g

In [ ]:
class Lin(LayerFunction):
    def __init__(self, w, b): self.w,self.b = w,b
        
    def forward(self, inp): return inp@self.w + self.b
    
    def bwd(self, out, inp):
        inp.g = out.g @ self.w.t()
        self.w.g = inp.t() @ self.out.g
        self.b.g = out.g.sum(0)

In [ ]:
class Mse(LayerFunction):
    def forward (self, inp, targ): return (inp.squeeze() - targ).pow(2).mean()
    def bwd(self, out, inp, targ): 
        inp.g = 2*(inp.squeeze()-targ).unsqueeze(-1) / targ.shape[0]

In [ ]:
from torch.autograd import Function

class MyRelu(Function):
    @staticmethod
    def forward(ctx, i):
        result = i.clamp_min(0.)
        ctx.save_for_backward(i)
        return result
    
    @staticmethod
    def backward(ctx, grad_output):
        i, = ctx.saved_tensors
        return grad_output * (i>0).float()

In [ ]:
import torch.nn as nn

class LinearLayer(nn.Module):
    def __init__(self, n_in, n_out):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(n_out, n_in) * sqrt(2/n_in))
        self.bias = nn.Parameter(torch.zeros(n_out))
    
    def forward(self, x): return x @ self.weight.t() + self.bias

In [ ]:
lin = LinearLayer(10,2)
p1,p2 = lin.parameters()
p1.shape,p2.shape

In [ ]:
class Model(nn.Module):
    def __init__(self, n_in, nh, n_out):
        super().__init__()
        self.layers = nn.Sequential(
            nn.Linear(n_in,nh), nn.ReLU(), nn.Linear(nh,n_out))
        self.loss = mse
        
    def forward(self, x, targ): return self.loss(self.layers(x).squeeze(), targ)

In [ ]:
class Model(Module):
    def __init__(self, n_in, nh, n_out):
        self.layers = nn.Sequential(
            nn.Linear(n_in,nh), nn.ReLU(), nn.Linear(nh,n_out))
        self.loss = mse
        
    def forward(self, x, targ): return self.loss(self.layers(x).squeeze(), targ)

## Conclusion

## Questionnaire

1. Write the Python code to implement a single neuron.
1. Write the Python code to implement ReLU.
1. Write the Python code for a dense layer in terms of matrix multiplication.
1. Write the Python code for a dense layer in plain Python (that is, with list comprehensions and functionality built into Python).
1. What is the "hidden size" of a layer?
1. What does the `t` method do in PyTorch?
1. Why is matrix multiplication written in plain Python very slow?
1. In `matmul`, why is `ac==br`?
1. In Jupyter Notebook, how do you measure the time taken for a single cell to execute?
1. What is "elementwise arithmetic"?
1. Write the PyTorch code to test whether every element of `a` is greater than the corresponding element of `b`.
1. What is a rank-0 tensor? How do you convert it to a plain Python data type?
1. What does this return, and why? `tensor([1,2]) + tensor([1])`
1. What does this return, and why? `tensor([1,2]) + tensor([1,2,3])`
1. How does elementwise arithmetic help us speed up `matmul`?
1. What are the broadcasting rules?
1. What is `expand_as`? Show an example of how it can be used to match the results of broadcasting.
1. How does `unsqueeze` help us to solve certain broadcasting problems?
1. How can we use indexing to do the same operation as `unsqueeze`?
1. How do we show the actual contents of the memory used for a tensor?
1. When adding a vector of size 3 to a matrix of size 3×3, are the elements of the vector added to each row or each column of the matrix? (Be sure to check your answer by running this code in a notebook.)
1. Do broadcasting and `expand_as` result in increased memory use? Why or why not?
1. Implement `matmul` using Einstein summation.
1. What does a repeated index letter represent on the left-hand side of einsum?
1. What are the three rules of Einstein summation notation? Why?
1. What are the forward pass and backward pass of a neural network?
1. Why do we need to store some of the activations calculated for intermediate layers in the forward pass?
1. What is the downside of having activations with a standard deviation too far away from 1?
1. How can weight initialization help avoid this problem?
1. What is the formula to initialize weights such that we get a standard deviation of 1 for a plain linear layer, and for a linear layer followed by ReLU?
1. Why do we sometimes have to use the `squeeze` method in loss functions?
1. What does the argument to the `squeeze` method do? Why might it be important to include this argument, even though PyTorch does not require it?
1. What is the "chain rule"? Show the equation in either of the two forms presented in this chapter.
1. Show how to calculate the gradients of `mse(lin(l2, w2, b2), y)` using the chain rule.
1. What is the gradient of ReLU? Show it in math or code. (You shouldn't need to commit this to memory—try to figure it using your knowledge of the shape of the function.)
1. In what order do we need to call the `*_grad` functions in the backward pass? Why?
1. What is `__call__`?
1. What methods must we implement when writing a `torch.autograd.Function`?
1. Write `nn.Linear` from scratch, and test it works.
1. What is the difference between `nn.Module` and fastai's `Module`?

### Further Research

1. Implement ReLU as a `torch.autograd.Function` and train a model with it.
1. If you are mathematically inclined, find out what the gradients of a linear layer are in mathematical notation. Map that to the implementation we saw in this chapter.
1. Learn about the `unfold` method in PyTorch, and use it along with matrix multiplication to implement your own 2D convolution function. Then train a CNN that uses it.
1. Implement everything in this chapter using NumPy instead of PyTorch. 

## Xtra

### myMatMul by hand
Try diff dstructs and measure time

In [ ]:
#myMatMul by hand 
#dstructs: lists
def myMatMul(m1, m2):
    ar,ac = m1.shape
    br,bc = m2.shape
    #print((ar,ac), (br,bc))
    assert ac==br

    c=[]

    for a_r in range(ar): #5 rows in m1
        c_r=[]
        
        for b_c in range(bc): #10 cols in m2
            c_val=[]

            for b_r in range(br): #784 rows in m2
                c_val.append(m1[a_r,b_r] * m2[b_r,b_c])

            c_r.append(sum(c_val))

        c.append(c_r)

    #print (len(c))
    return c

#myMatMul1 by hand
#dstructs: np array
def myMatMul1(m1, m2):
    ar,ac = m1.shape
    br,bc = m2.shape
    assert ac==br

    c=np.zeros((ar, bc), dtype=float)
    
    for a_r in range(ar): #5 rows in m1
        #print(a_r)

        for b_c in range(bc): #10 cols in m2
            c_sum = 0
            
            for b_r in range(br): #784 rows in m2
                c_val = m1[a_r,b_r] * m2[b_r,b_c]
                c_sum += c_val
                    
            c[a_r, b_c] = c_sum

    #print (len(c))
    return c

#myMatMul2 by hand - cleaner code but slower than myMatMul1
#dstructs: np array
def myMatMul2(m1, m2):
    ar,ac = m1.shape
    br,bc = m2.shape
    assert ac==br

    c=np.zeros((ar, bc), dtype=float)
    
    for a_r in range(ar): #5 rows in m1
        
        for b_c in range(bc): #10 cols in m2
            
            for b_r in range(br): #784 rows in m2
                c[a_r, b_c] += m1[a_r,b_r] * m2[b_r,b_c]
                    
    #print (len(c))
    return c

#myMatMul3 by hand - same as myMatMul2, only diff dstruct
#dstructs: torch array
def myMatMul3(m1, m2):
    ar,ac = m1.shape
    br,bc = m2.shape
    assert ac==br

    c = torch.zeros(ar, bc)
    
    for a_r in range(ar): #5 rows in m1
        
        for b_c in range(bc): #10 cols in m2
            
            for b_r in range(br): #784 rows in m2
                c[a_r, b_c] += m1[a_r,b_r] * m2[b_r,b_c]
                    
    #print (len(c))
    return c

In [ ]:
#$xtra my small 2x2 * 2x3 = 2x3 matrix
m1 = tensor([[1, 2], [3, 4]])
m2 = tensor([[1, 2, 3], [4, 5, 6]])

m1, m2

In [ ]:
%time t1=matmul(m1, m2)
%time m31=myMatMul1(m1,m2)
%time m32=myMatMul2(m1,m2)
%time m33=myMatMul3(m1,m2)
%time torch_matmul=torch.matmul(m1,m2)

Can do faster with elementwise multiplcation - no loop k

In [ ]:
#no loop k -> use elementwise multiplication instead
def myMatMul(a,b):
    ar,ac = a.shape # n_rows * n_cols
    br,bc = b.shape
    assert ac==br
    c = np.zeros((ar, bc), dtype=int32)
    for i in range(ar): #2 rows in m1
        for j in range(bc):
            c[i,j]=(a[i]*b[:,j]).sum()
        
    return c

matmul(m1,m2)

In [ ]:
#no loop j -> use broadcasting instead
def matmul(a,b):
    ar,ac = a.shape
    br,bc = b.shape
    assert ac==br
    c = np.zeros((ar, bc), dtype=int)
    for i in range(ar):
        c[i] = (a[i] * b.T).sum(1)
    return c

matmul(m1,m2)

In [ ]:
#no loop j -> use broadcasting instead
def matmul(a,b):
    ar,ac = a.shape
    br,bc = b.shape
    assert ac==br
    c = np.zeros((ar, bc), dtype=int)
    print (a.dot(b))
    #c = (a * b.T) #.sum(1)
    #return c

matmul(m1,m2)

### Shapes and Reshaping

In [ ]:
#$xtra numpy shapes and reshaping
c = np.array([10.,20,30]) #a vector with 3 elements
c_reshaped = c.reshape((3,1))
m = np.array([[1., 2, 3], [4,5,6], [7,8,9]])
print(c.shape, c_reshaped.shape, m.shape)

c + m, c_reshaped + m
#c, c_reshaped

In [ ]:
#change the shape of our vector to make it a 3×1 matrix
print(m2[0].shape, m2[0].unsqueeze(-1).shape)
m2[0], m2[0].unsqueeze(-1)

In [ ]:
for i in range(ar):
        print(a[i]),
        print(a[i].unsqueeze(-1))